### ISSUE TITLE
Obsolete screenshots of Celestia in app stores

### ISSUE THREAD

**Issue by SpaceExplorer2008** [celestiamobile/celestia.mobi#45]
The Celestia Mobile screenshots featured in all app stores are obsolete, after all Celestia has updated its textures and data, not to mention hundreds of new addons. I think we also need it to be clearer about the existence of downloadable addons, which could be shown in the images.

Although this is not a serious issue, I think we better update this.

**Comment by levinli303** [comment]
we need a curated list of cel URLs and descriptions text more suitable for App Store screenshots.

**Comment by Anthony-B-Russo10** [comment]
There also needs to be a screen shot showing that addons can also be downloaded on the appstore pages. I figured an image like this one would work for showing addons.
![Screenshot_20221025-151952](https://user-images.githubusercontent.com/57239744/204340328-16097552-3b76-4f82-89d0-82ede67466b3.png)

**Comment by SpaceExplorer2008** [comment]
My suggestions:

Look up Information about Stars, Planets and More: ![Screenshot_20221128-144223_Celestia.jpg](https://user-images.githubusercontent.com/99847641/204346778-2d34a39b-91cb-42d5-a72a-bdf6f7a86a07.jpg)

Relive Historical Events:![Screenshot_20221128-144408_Celestia.jpg](https://user-images.githubusercontent.com/99847641/204346872-e7754de7-22d3-467b-a6b6-fb2a3c14fd8f.jpg)

Real Time Simulation: ![Screenshot_20221128-144912_Celestia.jpg](https://user-images.githubusercontent.com/99847641/204346932-7b0e500b-d6f7-4e02-94b5-f46532031401.jpg)

**Comment by levinli303** [comment]
I'll think about it later. to be consistent across platforms, the app screenshots in the App Store now are actually generated through a program, not by manually taking screenshots on device. so it will be some code to write to show pages other than just the rendered scene.

**Comment by TheLostProbe** [comment]
> For "Explore the Outer Space" I used a different nebula with a sprite model, it might be more flashy:

looks nice but the galaxy brightness should be toned down so the nebula stands out more, it will look better that way

**Comment by levinli303** [comment]
we need new URLs and new text

**Comment by TheLostProbe** [comment]
from what i understand, the app store images are not screenshots of celestia but rather "generated by a program", correct? so how does the text work, then? do i just give you the text and it is converted into whichever special format the app store requires?

**Comment by levinli303** [comment]
> from what i understand, the app store images are not screenshots of celestia but rather "generated by a program", correct? so how does the text work, then? do i just give you the text and it is converted into whichever special format the app store requires?

1. automation tools to take screenshots based on URLs and save to disk
2. use a program to add the title text to each screenshot with the same style (white text on iOS/macOS blur)

so we just need URL and title text

**Comment by TheLostProbe** [comment]
okay, i'll see what i can come up with

**Comment by TheLostProbe** [comment]
so i have some preliminary screenshots and text (of course cel://URLs as well). the text is probably bound to change, and i also have yet to remake the "relive historical events" screenshot, as the cassini addon has compatibility issues with stock celestia's cassini.
ive decided to not just reword some of the texts, but also add new ones. for some of them, i couldnt decide on which screenshot was best, so just pick whatever one you think looks best. i will highlight those ones in **bold**. new text will be at the top in quotation marks, and the old text that it replaces will be in italics. if it doesnt say what it replaces, then it will instead just be a new image entirely

"Look Up Information On Stars, Planets, And More"
_Replaces "Look up Information about Stars, Planets, and More"_
 cel://Follow/Sol:Earth/2022-12-16T12:11:33.33082Z?x=oOtGUlHsv/7//////////w&y=lH9a9/+2Rg&z=eOxzMALSdf///////////w&ow=0.55236083&ox=0.14125372&oy=0.82113796&oz=0.026026227&select=Sol:Earth&fov=14.475634&ts=1&ltd=0&p=0&rf=205445015&nrf=255&lm=2048&tsrc=0&ver=3
![Look Up Information On Stars, Planets, And More](https://user-images.githubusercontent.com/67564416/208220738-3f385bd2-5c08-4b8c-bc38-f784ec305d4e.png)

"Relive Historical Events"
**Not done**

"Real-time Simulation Of Space"
_Replaces "Real Time Simulation"_
 cel://Follow/Sol:Jupiter:Callisto/2022-12-29T13:02:21.24573Z?x=0EFPSCT9F////////////w&y=BmRHSaN8Eg&z=MIAHvTU8qP///////////w&ow=0.54309326&ox=-0.06545507&oy=0.83556646&oz=0.050931282&select=Sol:Jupiter:Callisto&fov=6.1299043&ts=1&ltd=0&p=0&rf=205445015&nrf=255&lm=2048&tsrc=0&ver=3
![Real-time Simulation Of Space](https://user-images.githubusercontent.com/67564416/208220752-351360fa-7dac-4670-98d9-c664ecb8eaec.png)

**"Explore The Known Universe", option 1**
_Replaces "Explore the Outer Space"_
 cel://Follow/Abell%207/2022-12-16T12:15:00.62247Z?x=AAAAALCdE75EMj///////w&y=AAAAAMgpyNqfmDz//////w&z=AAAAAGwlGEbd1nA&ow=0.65527683&ox=-0.5153391&oy=0.11648787&oz=0.5398782&select=Abell%207&fov=14.475634&ts=1&ltd=0&p=0&rf=205445015&nrf=255&lm=2048&tsrc=0&ver=3
![(1) Explore The Known Universe](https://user-images.githubusercontent.com/67564416/208220583-f4a8909d-a250-4939-b7de-758b4296a3c4.png)

**"Explore The Known Universe", option 2**
_Replaces "Explore the Outer Space"_
cel://Follow/Westerhout%2051/2022-12-16T04:50:13.95181Z?x=AAAAAADehUISqN7h/////w&y=AAAAAABU9/H2YZAQ&z=AAAAACCdFYTK9iAC&ow=0.6373956&ox=0.53932494&oy=0.32490343&oz=-0.44417697&select=Westerhout%2051&fov=14.475634&ts=1&ltd=0&p=0&rf=205445015&nrf=255&lm=2048&tsrc=0&ver=3
![(2) Explore The Known Universe](https://user-images.githubusercontent.com/67564416/208220600-69164df6-8717-446b-8a7c-e9e3e8523b16.png)

**"Stunning And Realistic Graphics", option 1. Text may be changed in the future**
cel://Follow/Sol:Saturn/2029-10-08T17:29:11.41940Z?x=QA5JTLyKZ/3//////////w&y=1BGVQCtEPQ&z=gBACMAOaavb//////////w&ow=-0.024031289&ox=0.07931858&oy=-0.9965278&oz=-0.007966335&select=Sol:Saturn&fov=14.475634&ts=1&ltd=0&p=0&rf=205445015&nrf=255&lm=2048&tsrc=0&ver=3
![(1) Stunning And Realistic Graphics](https://user-images.githubusercontent.com/67564416/208220586-4c338f4d-4379-4b9e-9b6d-413bcb1d2f7e.png)

**"Stunning And Realistic Graphics", option 2. Text may be changed in the future**
cel://Follow/Sol:Saturn/2029-10-08T17:31:00.75524Z?x=sBzn/Rm2/v7//////////w&y=0AhBqvL6TgE&z=AKLoSFBPPOz//////////w&ow=0.016952747&ox=0.13201164&oy=-0.989903&oz=-0.04876145&select=Sol:Saturn&fov=14.556272&ts=1&ltd=0&p=0&rf=205445015&nrf=255&lm=2048&tsrc=0&ver=3
![(2) Stunning And Realistic Graphics](https://user-images.githubusercontent.com/67564416/208220625-d65bdc03-6a03-438b-8cc1-d2c1257b1d1e.png)

"Enhance Your Celestia Experience With Add-ons"
 cel://Follow/Cygnus%20X-1/2022-12-16T23:11:57.94245Z?x=ANJh4Db8Ovb//////////w&y=EITP3yFVuQ&z=OPTXLW94+Q&ow=0.7684056&ox=0.12378075&oy=0.6219163&oz=-0.086320505&select=Cygnus%20X-1&fov=14.475634&ts=1&ltd=0&p=0&rf=205445015&nrf=255&lm=2048&tsrc=0&ver=3
![Enhance Your Celestia Experience With Add-ons](https://user-images.githubusercontent.com/67564416/208220727-ce4049dd-88f2-4e85-8db2-ea9e32ec8b8d.png)

"Scientifically-accurate Simulation Of Space"
cel://Follow/Sol/2024-01-11T01:56:52.13252Z?x=AABgteEERHjQAQ&y=AABAASRKA5+TAw&z=AAAAAdt2DglE+v///////w&ow=-0.11243869&ox=0.081805296&oy=0.95028406&oz=0.2786138&select=Sol&fov=14.475634&ts=1&ltd=0&p=0&rf=205445047&nrf=255&lm=6151&tsrc=0&ver=3
![Scientifically-accurate Simulation Of Space](https://user-images.githubusercontent.com/67564416/208220767-e1d66525-f35d-4936-9f0a-58ca6d9c9e77.png)

"Your Companion For Stargazing"
cel://SyncOrbit/Sol:Earth/2024-08-30T15:14:01.19552Z?x=XXaSVpHn9f///////////w&y=rE24LnS6Kg&z=5Q2nfEwK+////////////w&ow=0.018914364&ox=-0.09317433&oy=0.9845414&oz=-0.14710201&select=Sol:Earth&fov=35.80111&ts=1&ltd=0&p=0&rf=205453215&nrf=255&lm=15&tsrc=0&ver=3
![Your Companion For Stargazing](https://user-images.githubusercontent.com/67564416/208220786-b2e0a045-5491-45c9-a791-dc099a037ef8.png)

i was also thinking that instead of having every first letter in each word capitalized, it could just be all lowercase. its a very commonly used modern design choice and also imo looks better than having each first letter capitalized
**example:**
![(2) Explore The Known Universe (lowercase text example)](https://user-images.githubusercontent.com/67564416/208224532-e0d954c5-8d48-4759-96bd-5d7ec1f85e0b.png)

**Comment by levinli303** [comment]
I'm also looking to change the text style, the current white on blur is not really the best one to show text, and I've lost the code for generating them anyway.

What I'm thinking is
1. Remove all HUD information text on screen
2. Place bigger (white) text on bottom right with no background, in two lines (aligned to the right side). The first line being a verb with bigger font. For example:

```
           Explore
The known universe
```

**Comment by TheLostProbe** [comment]
that text design... i swear ive seen something like that before somewhere. i suppose i can make a concept draft in GIMP tomorrow, and maybe experiment with different styles (like aligning it to the left and changing the margin etc.). also i think there should definitely be at least one screenshot of the HUD and UI so people know what the program looks like when youre using it

**Comment by levinli303** [comment]
an example here: <img width="960" alt="test" src="https://user-images.githubusercontent.com/17924287/208926257-810f2479-acd1-4ff3-b288-36df0a1b9005.png">

> i suppose i can make a concept draft in GIMP tomorrow, and maybe experiment with different styles (like aligning it to the left and changing the margin etc.).

you can experiment and start a vote somewhere

> also i think there should definitely be at least one screenshot of the HUD and UI so people know what the program looks like when youre using it

Only UI (of add-on page or info page UI), not HUD. So for each screenshot, we will need

1. cel URL
2. add-on ID if exists (at most two screenshots)
3. show info page or not (at most one screenshot)
4. caption

**Comment by levinli303** [comment]
@TheLostProbe  any updates?

**Comment by exl001** [comment]
Heres a trailer i made for the celestia mobi...
Hope you enjoy! :)

https://youtu.be/74l8xLRXHOY

**Comment by exl001** [comment]
> There also needs to be a screen shot showing that addons can also be downloaded on the appstore pages. I figured an image like this one would work for showing addons. ![Screenshot_20221025-151952](https://user-images.githubusercontent.com/57239744/204340328-16097552-3b76-4f82-89d0-82ede67466b3.png)

Where did you get the background orion nebula from? 😮

**Comment by levinli303** [comment]
> Heres a trailer i made for the celestia mobi... Hope you enjoy! :)
> 
> https://youtu.be/74l8xLRXHOY

This is amazing. I'd like to put the video on the App Stores.

For Google Play, the requirement is listed here:
https://support.google.com/googleplay/android-developer/answer/9866151?hl=en#zippy=%2Cpreview-video
Your preview video may also be displayed on both home and search page.
Your preview video may autoplay inline with muted audio up to 30 seconds depending on the user device, setting, network connection, and surface area. Whenever your video does not autoplay, a play button is overlaid on your feature graphic.
For games, some sections of Google Play show groups of recommended games in a large format using preview videos.

For Apple App Store:
The requirement is listed here: https://developer.apple.com/support/app-previews/
Most notably:
Each preview should be between 15 and 30 seconds long and will appear in all countries and regions where your app is available.

**Comment by TheLostProbe** [comment]
so there's a slight problem with my plan, which is that i can't copy the cel://URLs in any way, it just copies the name of whatever body is selected ("Earth", "Callisto", "Saturn" etc.)

i can definitely make the images but they won't be of any use without the URLs

**Comment by levinli303** [comment]
> so there's a slight problem with my plan, which is that i can't copy the cel://URLs in any way, it just copies the name of whatever body is selected ("Earth", "Callisto", "Saturn" etc.)
> 
> i can definitely make the images but they won't be of any use without the URLs

share is broken on mobile, try desktop to get URLs

**Comment by levinli303** [comment]
> so there's a slight problem with my plan, which is that i can't copy the cel://URLs in any way, it just copies the name of whatever body is selected ("Earth", "Callisto", "Saturn" etc.)
> 
> i can definitely make the images but they won't be of any use without the URLs

Fixed in 1.5.22, will be live on Google Play soon

**Comment by TheLostProbe** [comment]
well, i allocated myself some time to make new images. i can make modifications if necessary

![Educate yourself](https://github.com/levinli303/celestia.mobi/assets/67564416/86122673-385f-4aa0-88ae-47750755120f)
URL: cel://Follow/Sol:Earth/2023-07-02T13:52:59.06554Z?x=gHqIoxcYrv7//////////w&y=JAcLdlkIUQ&z=ySumWO0O/v///////////w&ow=-0.73719114&ox=-0.26776052&oy=-0.6141897&oz=0.087318935&select=HIP%204385&fov=15.534161&ts=1&ltd=0&p=1&rf=71227287&nrf=255&lm=2048&tsrc=0&ver=3

![Traverse the Solar System](https://github.com/levinli303/celestia.mobi/assets/67564416/f869bb18-4f21-4fe1-a618-d4e870d1246e)
URL: cel://Follow/Sol/2023-06-10T04:01:09.36594Z?x=AADgxNkenTx7Ag&y=AAAAeu5N7SvJAw&z=AABAbpqtfATN+v///////w&ow=-0.1762914&ox=0.039147615&oy=0.9339327&oz=0.30847773&fov=15.497456&ts=1&ltd=0&p=0&rf=71227315&nrf=255&lm=6147&tsrc=0&ver=3

![Navigate the night sky](https://github.com/levinli303/celestia.mobi/assets/67564416/2479c2e9-6036-4fef-90ea-b3157179b194)
URL: cel://SyncOrbit/Sol:Earth/2024-07-30T06:00:31.79943Z?x=5H8ym9O86f///////////w&y=Jx39zwAGIw&z=6bKOqSApDw&ow=0.88020444&ox=-0.3483816&oy=0.18829681&oz=-0.26156196&select=TYC%204123-1214-1&fov=51.175&ts=1&ltd=0&p=1&rf=71235487&nrf=255&lm=15&tsrc=0&ver=3

![Explore the known universe](https://github.com/levinli303/celestia.mobi/assets/67564416/7590cdc6-aa6c-4165-ade8-e4b04d9689d5)
URL: cel://Follow/Westerhout%2051/2023-06-10T03:31:39.13768Z?x=AAAAAABxRUqY3KUS&y=AAAAAAA1xr8Nhgv2/////w&z=AAAAAAC8ueP73lXs/////w&ow=-0.4382953&ox=0.5837729&oy=0.678968&oz=0.07815942&fov=15.497456&ts=1&ltd=0&p=0&rf=71227287&nrf=255&lm=2048&tsrc=0&ver=3

![Simulate in real-time](https://github.com/levinli303/celestia.mobi/assets/67564416/72a1d414-b423-40d1-8f79-6483e72c99bc)
URL: cel://Follow/Sol:Jupiter:Callisto/2023-07-02T11:03:12.01362Z?x=YJG63ya8Sf///////////w&y=k1RN8wszCw&z=ZY4WNWkjGQ&ow=0.7285262&ox=-0.043709736&oy=0.682417&oz=0.0405734&fov=5.30302&ts=10&ltd=0&p=1&rf=71227287&nrf=255&lm=2048&tsrc=0&ver=3

![Enhance Celestia with add-ons](https://github.com/levinli303/celestia.mobi/assets/67564416/dd615e9b-53a2-4561-9e1f-1aad9ca23ab3)
URL: cel://Follow/Cygnus%20X-1/2023-07-02T13:52:59.06554Z?x=ACwEriWpVvv//////////w&y=cKpIoLiUl////////////w&z=AOyX+4hMTQg&ow=0.10665737&ox=-0.3053027&oy=-0.0070079123&oz=0.94623744&select=HD%20226868%20A&fov=15.534161&ts=10&ltd=0&p=1&rf=71227287&nrf=255&lm=2048&tsrc=0&ver=3

do we need more images, or is this enough?

**Comment by Anthony-B-Russo10** [comment]
That looks to be enough.

**Comment by levinli303** [comment]
@TheLostProbe they look good. although i think we can reword "Educate yourself"

**Comment by TheLostProbe** [comment]
i tried several other sentences for that one and they were either too long or just didn't make any sense. you requested that the first word of the sentence be a verb, so that kind of limits me in terms of what i can write. like yeah there are heaps of verbs, but i just couldn't find the right one for that particular sentence
i have the xcf files for all of them so changing the wording shouldn't be a problem

**Comment by levinli303** [comment]
"Learn about space" sounds good.

**Comment by TheLostProbe** [comment]
done, how does it look?
![Learn about space](https://github.com/levinli303/celestia.mobi/assets/67564416/f0a241a3-f134-4f6c-8c86-daa734ced147)

**Comment by levinli303** [comment]
I will re-generate images with scripts for all platforms based on the URLs and whether or not to show an Info/Addon view instead of using the ones provided here directly.

For fonts i will use the default ones on each platform to avoid issues, Apple screenshot will use San Francisco, Windows with Segoe, Android with Roboto.

**Comment by levinli303** [comment]
@TheLostProbe  can you point me to where the "EXPLORE the universe" add-on is

**Comment by TheLostProbe** [comment]
it should be [this](https://celestia.mobi/resources/item?item=2EA6D9A9-1DA9-AA6F-91DC-C384D60813D0)

**Comment by levinli303** [comment]
I've generated images for all platforms and start uploading them to app stores.

examples:
Android:
![Output5](https://github.com/levinli303/celestia.mobi/assets/17924287/8f366252-fd36-4071-b78f-69cd8fdcc26a)
iOS (iPhone):
![Output5](https://github.com/levinli303/celestia.mobi/assets/17924287/0c103b3e-6357-4dea-bbc9-ee13953c9ce3)
iOS(iPad):
![Output5](https://github.com/levinli303/celestia.mobi/assets/17924287/4ae67a30-4084-4e34-8ae2-6145d7dfb480)
macOS:
![Output5](https://github.com/levinli303/celestia.mobi/assets/17924287/b50bb04a-9a3a-4370-9bdf-840c51f7173e)
Windows:
![Output5](https://github.com/levinli303/celestia.mobi/assets/17924287/5a2e15df-aab0-4d65-8c73-678342ba4462)

**Comment by DaveBowman2001** [comment]
I can see the new screenshots now on PlayStore! They're all beautiful 
![IMG_20230620_221402](https://github.com/levinli303/celestia.mobi/assets/95486841/97beb214-aacc-4d4f-a81d-d145a8c6305a)

**Comment by DaveBowman2001** [comment]
Wait, the trailer wasn't yet attached?

**Comment by levinli303** [comment]
> Wait, the Celestia [trailer](https://youtu.be/74l8xLRXHOY) wasn't yet attached to the new screenshots?

trailer needs editing.

**Comment by levinli303** [comment]
its been two years, we should update screenshots again.
