### ISSUE TITLE
Trouble accessing CEL/CELX scripts installed from Add-on Categories

### ISSUE THREAD

**Issue by DaveBowman2001** [celestiamobile/celestia.mobi#78]
A few days ago, I've added Tom's [CEL scripts from the TTEC](https://celestia.mobi/resources/item?item=1973F4D9-5C84-4342-AFF4-723C6BBAFA25) as an experiment to see how they work on mobile Celestia
![Screenshot_2023-10-29-06-31-42-228_space celestia mobilecelestia](https://github.com/celestiamobile/celestia.mobi/assets/95486841/88e151cb-f5d7-43f0-bf56-67cf226133cd)
![IMG_20231029_063309](https://github.com/celestiamobile/celestia.mobi/assets/95486841/f9fb5b9c-5888-42bd-8219-47cfd83ea420)

However they are nowhere to be seen, not even the `Script Control` function:
![Screenshot_2023-10-29-06-32-12-462_space celestia mobilecelestia](https://github.com/celestiamobile/celestia.mobi/assets/95486841/2675465f-b13b-478f-bbc3-40ffdd8d755c)

Since Android 11 doesn't grant access to data folders, I unfortunately cannot move the individual scripts manually to the main scripts folder itself

**Comment by levinli303** [comment]
media folder is also read for scripts and this folder usually you have access even on Android 11+, so if you have scripts ready, you can move them (add-ons are installed to data folder so probably you cannot move from the add-on you downloaded):
https://celestia.mobi/resources/guide?guide=D1A96BFA-00BB-0089-F361-10DD886C8A4F

There are a couple issues here:
The submission system does not support Scripts. You'll see in https://celestia.mobi/resources/item?item=62C6E26B-D781-2C74-B0AF-74B0A06022AF which is a manually created Script, when you install it, the button changes to "Run" instead of "Go". I will work on that later.

Scripts are not installed to scripts folder. They are installed to "extras" folder, i still need to consider whether it should be installed to scripts folder instead. The intention of keeping them in extras instead of scripts folder comes from that i don't really plan for them to be run from Favorite -> Scripts

Script collection is not supported, there is only one "Run" button so there is not support for multiple scripts in a single script add-on.

**Comment by DaveBowman2001** [comment]
Yeah, CEL/CELX scripts should be placed on the scripts folder. I just followed the format from the Sound Demo but did not work in this case somehow

**Comment by levinli303** [comment]
> Yeah, CEL/CELX scripts should be placed on the scripts folder. I just followed the format from the Sound Demo but did not work in this case somehow

yeah after some thought i agree that they should be put in scripts folder. well this would solve the "script collection" issue too. however this requires changes to the code, so this will be in the release after 1.6.0

for the submission issue i will add an option for script add-ons.

**Comment by DaveBowman2001** [comment]
On existing script addons....do I need to resubmit them?

**Comment by levinli303** [comment]
> On existing script addons....do I need to resubmit them?

updating them, choose "Script" in Type

**Comment by levinli303** [comment]
Fixed in 1.6.1. Scripts will show up in Favorites -> Scripts
